---
title: "Submit Observations"
author: "Cathleen Balantic"
date: "March 16, 2018"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tips for submitting observations:
Only submit an observation for a species and location once per episode! e.g., if you already observed a Praire Warbler in the Dothraki Sea in S2E7, you don't need to submit it again every time it sings.

**Your Name**: No registration or real name is required or enforced. Just input some kind of identifier for yourself.   
**Species you observed (common name)**: Put down the common name of the species you observed. Since common names can differ geographically, you also have the option to input the **latin name** in the next field. 

**Location**: This can be tricky. If a location is available on the map, but not in the dropdown menu, that's because I'm at least 95% certain that location is only available in the book and never actually visited in the show -- we shouldn't have any bird observations there. If I've made a mistake here, just select "UNKNOWN" and explain yourself in the **Comments** field. Same with if you're not sure where a bird was observed -- select "UNKNOWN" option, describe the scene in the comments (which characters? was it day or night?), and definitely leave the **season**, **episode number**, and approximate **minute** of the episode. I'll sort out a location based on that info. 


